// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BilerOgEjere.Migrations
{
    [DbContext(typeof(BilContext))]
    [Migration("20230224150618_AddAgeField")]
    partial class AddAgeField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Bil", b =>
                {
                    b.Property<int>("BilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BilID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("Diesel")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("BilID");

                    b.ToTable("Bil");

                    b.HasData(
                        new
                        {
                            BilID = -1,
                            Age = 0,
                            Diesel = false,
                            Name = "Ford",
                            Weight = 1400
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
