// <auto-generated />
using Dag8_Opgave1_MinFørste_EF_App.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dag8_Opgave1_MinFørste_EF_App.Migrations
{
    [DbContext(typeof(BilContext))]
    [Migration("20230227111232_addAge")]
    partial class addAge
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dag8_Opgave1_MinFørste_EF_App.Model.Bil", b =>
                {
                    b.Property<int>("BILID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BILID"));

                    b.Property<bool>("Diesel")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weigth")
                        .HasColumnType("int");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.HasKey("BILID");

                    b.ToTable("Bil");

                    b.HasData(
                        new
                        {
                            BILID = -1,
                            Diesel = true,
                            Name = "Ford",
                            Weigth = 1400,
                            age = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
