// <auto-generated />
using Dag8_Opgave1_MinFørste_EF_App.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dag8_Opgave1_MinFørste_EF_App.Migrations
{
    [DbContext(typeof(BilContext))]
    partial class BilContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dag8_Opgave1_MinFørste_EF_App.Model.Bil", b =>
                {
                    b.Property<int>("BILID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BILID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("Diesel")
                        .HasColumnType("bit");

                    b.Property<int>("EjerPERSONID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weigth")
                        .HasColumnType("int");

                    b.HasKey("BILID");

                    b.HasIndex("EjerPERSONID");

                    b.ToTable("Bil");
                });

            modelBuilder.Entity("Dag8_Opgave1_MinFørste_EF_App.Model.Person", b =>
                {
                    b.Property<int>("PERSONID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PERSONID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PERSONID");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Dag8_Opgave1_MinFørste_EF_App.Model.Bil", b =>
                {
                    b.HasOne("Dag8_Opgave1_MinFørste_EF_App.Model.Person", "Ejer")
                        .WithMany("Biler")
                        .HasForeignKey("EjerPERSONID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejer");
                });

            modelBuilder.Entity("Dag8_Opgave1_MinFørste_EF_App.Model.Person", b =>
                {
                    b.Navigation("Biler");
                });
#pragma warning restore 612, 618
        }
    }
}
